# Generated by Django 3.1.1 on 2020-10-07 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('hyperlink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('course_number', models.IntegerField(blank=True, max_length=10)),
                ('instructor', models.CharField(blank=True, max_length=30)),
                ('section', models.IntegerField(blank=True, max_length=5)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.coursefields')),
            ],
        ),
    ]
