# Generated by Django 3.1.1 on 2020-10-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fields',
        ),
        migrations.AddField(
            model_name='course',
            name='fields',
            field=models.ManyToManyField(to='aggregator.CourseField'),
        ),
    ]
