# Generated by Django 3.1.1 on 2020-10-14 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
